name: "Setup Bun"
description: "Setup Bun with caching and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Cache Bun
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-
        path: ~/.bun

    - name: Setup Bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      with:
        bun-version-file: package.json

    - name: Install dependencies
      run: bun install
      shell: bash
